FROM tensorflow-build-gpu:1.3

#based on https://raw.githubusercontent.com/tensorflow/magenta/master/magenta/tools/docker/Dockerfile 
MAINTAINER Chester Kuo <chester.kuo@gmail.com> 

ENV http_proxy http://proxy-chain.intel.com:911
ENV https_proxy https://proxy-chain.intel.com:912
ENV HTTP_PROXY http://proxy-chain.intel.com:911
ENV HTTPS_PROXY https://proxy-chain.intel.com:912


ENV MAGENTA_REF v0.3.1

RUN apt-get update
RUN apt-get install -y libasound2-dev
# Required for local development
RUN pip install 'librosa>=0.5.1'
RUN pip install 'scipy>=0.18.1'
RUN pip install 'Pillow>=3.4.2'
RUN pip install 'bokeh>=0.12.0'
RUN pip install 'intervaltree>=2.1.0'
RUN pip install 'matplotlib >= 1.5.3'
RUN pip install 'mido==1.2.6'
RUN pip install 'numpy>=1.11.0'
RUN pip install 'pandas>=0.18.1'
RUN pip install 'pretty_midi>=0.2.6'
RUN pip install  futures python-rtmidi wheel

WORKDIR /
# Fix paths so that CUDNN can be found
# See https://github.com/tensorflow/tensorflow/issues/8264
RUN ls -lah /usr/local/cuda/lib64/*
RUN mkdir /usr/lib/x86_64-linux-gnu/include/ && \
  ln -s /usr/lib/x86_64-linux-gnu/include/cudnn.h /usr/lib/x86_64-linux-gnu/include/cudnn.h && \
  ln -s /usr/include/cudnn.h /usr/local/cuda/include/cudnn.h && \
  ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so /usr/local/cuda/lib64/libcudnn.so && \
  ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.6 /usr/local/cuda/lib64/libcudnn.so.6
RUN echo "/usr/local/cuda-8.0/targets/x86_64-linux/lib/stubs" >> /etc/ld.so.conf.d/cuda-8-0.conf
RUN ldconfig

RUN git clone https://github.com/tensorflow/magenta.git && \
    cd magenta && \
    git checkout $MAGENTA_REF
WORKDIR /magenta
# Temp work-around , should be remove after issue fix
# check https://github.com/tensorflow/tensorflow/issues/12979
RUN sed -ri "/^\W+sha256 = \"[^\"]+\"\W+$/d" WORKSPACE

RUN bazel build //magenta/... && bazel test --test_output=errors //magenta/...

RUN bazel build magenta/tools/pip:build_pip_package && \
    bazel-bin/magenta/tools/pip/build_pip_package /tmp/magenta_pkg && \
    bazel-bin/magenta/tools/pip/build_pip_package /tmp/magenta_pkg --gpu && \
    pip install --upgrade /tmp/magenta_pkg/magenta-*.whl

# Start an interactive shell

CMD ["bash"]
