FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
MAINTAINER Chester Kuo <chester.kuo@gmail.com>

ENV http_proxy http://proxy-chain.intel.com:911
ENV https_proxy https://proxy-chain.intel.com:912


ENV NEONBUILD /tmp/neon
RUN apt-get update
RUN apt-get -y install build-essential libopencv-dev
RUN apt-get -y install git curl vim-tiny 
RUN apt-get -y install python-pip libhdf5-dev libyaml-dev pkg-config 
RUN apt-get -y install clang
RUN apt-get -y install libcurl4-openssl-dev libsox-dev
RUN apt-get -y install cmake
RUN apt-get -y install wget doxygen

WORKDIR /tmp

CMD mkdir -p /tmp

RUN pip install --upgrade pip
RUN pip install virtualenv

#install Ninja
RUN cd /tmp && git clone https://github.com/ninja-build/ninja.git && cd ninja && ./configure.py --bootstrap && cp ninja /usr/local/bin/
#install aeon
RUN cd /tmp && git clone -b v1.0.0 https://github.com/NervanaSystems/aeon.git 
RUN cd /tmp/aeon && pip install -r requirements.txt 
RUN mkdir -p /tmp/aeon/build && cd /tmp/aeon/build && cmake .. && pip install .

ENV LD_LIBRARY_PATH /usr/local/cuda-8.0/targets/x86_64-linux/lib/stubs:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
ENV PATH /usr/local/cuda/bin:$PATH
#install mkl-dnn
RUN git clone https://github.com/01org/mkl-dnn.git
RUN cd mkl-dnn/scripts && ./prepare_mkl.sh && cd .. && mkdir -p build && cd build && cmake ../ && make && make install 
RUN git clone -b v2.1.0 https://github.com/NervanaSystems/neon.git ${NEONBUILD}
RUN cd ${NEONBUILD} && make sysinstall 

#install deepspeech
RUN git clone https://github.com/NervanaSystems/deepspeech.git && cd deepspeech && pip install -r requirements.txt && make
