FROM nvidia/cuda:8.0-cudnn6-devel-ubuntu16.04
MAINTAINER Chester Kuo <chester.kuo@gmail.com>

ENV http_proxy http://proxy-chain.intel.com:911
ENV https_proxy https://proxy-chain.intel.com:912


ENV TENSORFLOWBUILD /tmp/tensorflow-build
ENV TENSORFLOW_PACKAGE https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-1.3.0-cp27-none-linux_x86_64.whl 
ENV TENSORFLOW_EXAMPLE tensorflow-nmt
ENV TENSORFLOW_NMT_DATA "${TENSORFLOWBUILD}/${TENSORFLOW_EXAMPLE}/nmt_data"
ENV TENSORFLOW_NMT_MODEL "${TENSORFLOWBUILD}/${TENSORFLOW_EXAMPLE}/nmt_model"
ENV NMT_DOWNLOAD_SCRIPT download-wmt14.sh
#ENV NMT_SRC vi
ENV NMT_SRC de 
ENV NMT_TGT en


RUN apt-get update
RUN apt-get -y install git
RUN apt-get -y install python-pip 
RUN apt-get -y install curl
RUN apt-get -y install vim-tiny 
RUN apt-get -y install wget

WORKDIR ${TENSORFLOWBUILD}

CMD mkdir -p /tmp
CMD mkdir -p ${TENSORFLOWBUILD}

# for Tensorflow nightly build case 
RUN wget ${TENSORFLOW_PACKAGE}

RUN pip install ./*.whl 
RUN git clone https://github.com/tensorflow/nmt.git ${TENSORFLOWBUILD}/${TENSORFLOW_EXAMPLE}
RUN echo "/usr/local/cuda-8.0/targets/x86_64-linux/lib/stubs" >> /etc/ld.so.conf.d/cuda-8-0.conf
RUN ldconfig

RUN mkdir -p ${TENSORFLOW_NMT_DATA}
RUN mkdir -p ${TENSORFLOW_NMT_MODEL}
# COPY script
COPY ${NMT_DOWNLOAD_SCRIPT} ${TENSORFLOW_EXAMPLE}/nmt/scripts/
RUN /bin/sh ${TENSORFLOW_EXAMPLE}/nmt/scripts/${NMT_DOWNLOAD_SCRIPT} ${TENSORFLOW_NMT_DATA}
#RUN /bin/sh ${TENSORFLOW_EXAMPLE}/nmt/scripts/download_iwslt15.sh ${TENSORFLOW_NMT_DATA}

# run Trainning
# For Germany
RUN cd ${TENSORFLOW_EXAMPLE} && echo "python -m nmt.nmt --src=${NMT_SRC} --tgt=${NMT_TGT} --train_prefix=${TENSORFLOW_NMT_DATA}/train --vocab_prefix=${TENSORFLOW_NMT_DATA}/vocab.50k --dev_prefix=${TENSORFLOW_NMT_DATA}/tst2012 --test_prefix=${TENSORFLOW_NMT_DATA}/tst2013 --out_dir=${TENSORFLOW_NMT_MODEL} --num_train_steps=12000 --steps_per_stats=100 --num_layers=2 --num_units=128 --dropout=0.2 --metrics=bleu" > train-nmt-de.sh

# for Vietnamese
#RUN cd ${TENSORFLOW_EXAMPLE} && echo "python -m nmt.nmt --src=${NMT_SRC} --tgt=${NMT_TGT} --train_prefix=${TENSORFLOW_NMT_DATA}/train --vocab_prefix=${TENSORFLOW_NMT_DATA}/vocab --dev_prefix=${TENSORFLOW_NMT_DATA}/tst2012 --test_prefix=${TENSORFLOW_NMT_DATA}/tst2013 --out_dir=${TENSORFLOW_NMT_MODEL} --num_train_steps=1000 --steps_per_stats=100 --num_layers=2 --num_units=128 --dropout=0.2 --metrics=bleu" > train-nmt.sh

RUN chmod 755 ${TENSORFLOWBUILD}/${TENSORFLOW_EXAMPLE}/train-nmt-de.sh
